### ISSUE TITLE
Feature Extraction

### ISSUE THREAD

**Issue by davidsbatista** [davidsbatista/BREDS#1]
The process of feature extraction can be parallelized by first loading all the files into a Queue and then launch separate processes/threads do generate Tuples from each of sentence.

**Comment by davidsbatista** [comment]
print "Loading sentences into Queue"
            f_sentences = codecs.open(sentences_file, encoding='utf-8')
            count = 0
            for line in f_sentences:
                queue.put(line.strip())
                count += 1
                if count % 10000 == 0:
                    sys.stdout.write(".")
            f_sentences.close()
            print "\nDone all"

            print "\nGenerating relationship instances from sentences"
            results = [m.list() for _ in range(num_cpus)]
            processes = [multiprocessing.Process(target=self.find_relationships, args=(queue, results[i]))
                         for i in range(num_cpus)]

            print "Launching", num_cpus, "processes"
            for proc in processes:
                proc.start()
            for proc in processes:
                proc.join()

            all_results = list()
            for l in results:
                all_results.extend(l)

            for t in all_results:
                self.processed_tuples.append(t)

            print len(self.processed_tuples), "tuples generated"
            print "Writing generated tuples to disk"
            f = open("processed_tuples.pkl", "wb")
            cPickle.dump(self.processed_tuples, f)
            f.close()

**Comment by ekipowerx** [comment]
Whats happening in automatic-evaluation folder files.

**Comment by davidsbatista** [comment]
- Its an implementation of this paper: https://akbcwekex2012.files.wordpress.com/2012/05/8_paper.pdf
- But I don't know how easy it is to understand that code, when I have time I will write a tutorial on how to use BREDS and perform an evaluation;

**Comment by ekipowerx** [comment]
Thanx
