### ISSUE TITLE
Questions about usage of negative seeds

### ISSUE THREAD

**Issue by Hongtao-Lin** [davidsbatista/BREDS#11]
According to the paper: Semi-Supervised Bootstrapping of Relationship Extractors with Distributional Semantics, it looks like only positive seeds are used in algorithm. Would you mind explaining more on the usage of negative seeds here?

**Comment by davidsbatista** [comment]
The idea is from this paper:

[Extracting synonymous gene and protein terms from biological literature](https://www.researchgate.net/publication/10667374_Extracting_Synonymous_Gene_and_Protein_Terms_From_Biological_Literature
)

which is also from one of the authors of Snowball
