### ISSUE TITLE
pattern2vector_sum function in tuple.py retrieving character word vector

### ISSUE THREAD

**Issue by zqyeo** [davidsbatista/BREDS#12]
In tuple.py, lines 72, 78 and 79 passes bet_filtered, bef_no_tags and and aft_no_tags to function pattern2vector_sum. Note that these variables passed are only the literal words (without POS tags). 

However, at line 87, the word vector retrieval appears to be retrieving the zero-th position character of the token passed into this function instead of the expected vector retrieval of the entire word.

i.e. 
line 87 :: vector = config.word2vec[t[0].strip()]

Changing line 87 to 
vector = config.word2vec[t.strip()]

works for me.

**Comment by davidsbatista** [comment]
Thanks! That was a very nasty bug...it's corrected now :)
