### ISSUE TITLE
Clarification of pattern.py line 18 

### ISSUE THREAD

**Issue by zqyeo** [davidsbatista/BREDS#13]
Line 18: if tuple is not None:
Line 19:      self.tuples.add(t)

tuple is a Python keyword for the tuple class, and the statement in Line 18 will always return True.

Should it be:

if t is not None:
     self.tuples.add(t)

? Thank you.

**Comment by davidsbatista** [comment]
You are totally correct, this was a distraction/silly thing, thanks once again for keeping an eye for this kind of bugs. I will submit a correction in a few minutes.

**Comment by zqyeo** [comment]
No problem!
Great work by the way.
> You are totally correct, this was a distraction/silly thing, thanks once again for keeping an eye for this kind of bugs. I will submit a correction in a few minutes.
