### ISSUE TITLE
No negative seed update

### ISSUE THREAD

**Issue by davebulaval** [davidsbatista/BREDS#18]
It seem like the negative seeds aren't updated.

````
for t in list(self.candidate_tuples.keys()):
                    if t.confidence >= self.config.instance_confidence:
                        seed = Seed(t.e1, t.e2)
                        self.config.positive_seed_tuples.add(seed)
````
Only the positive is updated.

**Comment by davidsbatista** [comment]
I took the idea of negative examples from this paper:

- H Yu, E Agichtein, [Extracting synonymous gene and protein terms from biological literature](http://bioinformatics.oxfordjournals.org/content/19/suppl_1/i340.full.pdf). In Bioinformatics, 19(suppl 1), 2003 - Oxford University Press

and as far as I remember I did not intended to update the negative seeds set, the idea was just to give some pairs of entities that you know that occur together but don't express the relationship you want to extract.
