### ISSUE TITLE
If new tuples are found, do i need to tag the new entities in the document collection?

### ISSUE THREAD

**Issue by nixondevph** [davidsbatista/BREDS#20]

**Comment by davidsbatista** [comment]
Sorry, I don't understand you question, tuples should contain already tagged entities, what do you mean exactly? Can you maybe give an example?

**Comment by nixondevph** [comment]
What if the new entities are not tagged but found by the pattern (ex., is based in)? like "SoundCloud is based in Berlin." -> (SoundCloud, Berlin). Should I tag these newly found entities in the document collection?

Im working on a different domain that has no state-of-the-art NER (not PER/LOC/ORG).

Thank you!

**Comment by davidsbatista** [comment]
You should first tag all your documents, and then apply the bootstrapping process.
