### ISSUE TITLE
Commands to replicate F1-score of BREDS

### ISSUE THREAD

**Issue by unktkn** [davidsbatista/BREDS#21]
Hi there,

Can you please include the exact commands with parameters (including running pre_processing_KB scripts: `easy_freebase_clean.py`, `select_sentences.py` and `index_whoosh.py`) to replicate evaluation numbers of BREDS reported in paper?
Thanks for adding some notes for the `ReadMe` for automatic-evaluation, but it would really help us if you can also include the exact commands.
[I would really appreciate a timely reply]

Thank you!

**Comment by unktkn** [comment]
Interestingly in [Sentence.py ](https://github.com/davidsbatista/BREDS/blob/master/automatic-evaluation/pre_processing_KB/select_sentences.py#L129), entities lookup in freebase will fail as in Freebase `Microsoft` is represented as `Microsoft Organization` and in the data it is mentioned without the organization; and because of this quite many valid sentences will be ignored. So either entities should be normalized according to Freebase (or any other KB) or a partial search of entity mentions should be done.

**Comment by unktkn** [comment]
Also kb lookup ignore to take into account the relation type for which look-up is being performed; with the current code KB lookup will return positive result because both entities were found in a KB even for a totally different relation.

**Comment by davidsbatista** [comment]
Hello! Thanks for your feedback.

I remember going through the problems you stated and I remember writing scripts to do it, but as I've said I lost part of that code.

As I wrote in the README.MD the code inside `pre_processing_KB` lacks maintenance and is incomplete, plus there's code missing (normalizing named-entities and relationships) which got lost in some server were the experiments ran.
