### ISSUE TITLE
Clarification regarding Automatic-Evaluation

### ISSUE THREAD

**Issue by unktkn** [davidsbatista/BREDS#22]
Hi,

Sorry for bothering again regarding the automatic-evaluation but this is important for me to know.
In [`large-scale-evaluation-freebase.py`](https://github.com/davidsbatista/BREDS/blob/master/automatic-evaluation/large-scale-evaluation-freebase.py#L269) while loading freebase the whole KB is loaded irrespective of the relation type, now consider [`string_matching_parallel()`](https://github.com/davidsbatista/BREDS/blob/master/automatic-evaluation/large-scale-evaluation-freebase.py#L732) it is only checked if `e1` and `e2` occur in the KB but not for which relation? which means if my model predicts a `Founder-Of` relation between `Marissa Mayer` and `Google` than it will be correct becasuse of this line:
 ``if len(database_1[(r.ent1.decode("utf8"),  r.ent2.decode("utf8"))]) > 0:``
But KB actually contained `Marissa Mayer Employment history Google`.
Is my understanding correct that it is only checked if two entites occur in a database but not for which relation? (please indicate yes/no for the `Marissa Mayer Founder-Of Google` example).

Many Thanks!

**Comment by davidsbatista** [comment]
I remember filtering the Freebase and DBpedia only for the relationships I wanted to evaluate.

I'm sorry, but as I said before, there's code missing on "automatic-evaluation", plus I haven't touched/looked to any this code since 2014/2015.
