### ISSUE TITLE
Calculating tuples confidence

### ISSUE THREAD

**Issue by uyaseen** [davidsbatista/BREDS#4]
Hi,

Thank you for sharing your (clean) code. In the parallel version of BREDS when computing the '[tuples confidence](https://github.com/davidsbatista/BREDS/blob/master/BREDS-parallel.py#L597)' why you are taking a weighted combination of confidence score from last & current iteration. I understand `self.config.wUpdt` is a hyperparameter but still why is it needed only in the parallel version ?

**Comment by davidsbatista** [comment]
Hi Uyaseen,

sorry for the delayed version, I think that at a certain point I just started working on the parallel-version, and as a consequence I only add to that version. It's taken from the original Snowball paper:

http://www.mathcs.emory.edu/~eugene/papers/dl00.pdf (page 5)
