### ISSUE TITLE
Missing requirements.txt file

### ISSUE THREAD

**Issue by luckylu91** [davidsbatista/BREDS#5]
Hi !
I can't find the **requirements.txt** file that you evoke in your readme.md.
This causes me having an error at the call of the method `jellyfish.jaro_winkler` at lines 787-789 of the script **large-scale-evaluation-freebase.py** located in **/automatic-evaluation/**. I think that my version of jellyfish is too recent as compared to yours.
If you still have it, could you please add it to the repo ?

By the way I fixed this script for windows users (there is a difference in the behavior of the `multiprocessing` package between windows and linux, look at [http://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/](url) if you are interrested). Tell me if you would like to see what I have changed.

Thank you for your work, I really appreciate it !

**Comment by davidsbatista** [comment]
Hi, thanks for reporting that error. I've added a README.MD to the automatic evaluation, unfortunately this code lacks of good principles and I currently lack the time to refactor it. I nevertheless left some tips there on how to generate a golden standard for evaluation given a KB.

I will know focus on fixing BREDS (writing proper tests, and porting it to Python3) and later on pick up the evaluation bit.

Thanks
