### ISSUE TITLE
Several errors when running /automatic-evaluation/large-scale-evaluation-freebase.py

### ISSUE THREAD

**Issue by luckylu91** [davidsbatista/BREDS#6]
Hi again !

The errors mentionned in the title are due to the use of Sentence.py (`from BREDS.Sentence import Sentence` at line 15 of `large-scale-evaluation-freebase.py`)
At the begining I assumed that using the module Sentence.py located in /BREDS/ would work. But in fact, I found clues that you may have used a different version of this module when developping `large-scale-evaluation-freebase.py`.

The clues are :
- In the `/BREDS/Sentence.py` file, you don't handle the case where the `pos_tagger` and `config` arguments of `__init__` are `None` (which happen to be the case in the call at line 141 of `large-scale-evaluation-freebase.py`)
- In `large-scale-evaluation-freebase.py`, in `process_corpus()`, line 144 you wrote `tokens = word_tokenize(r.between)` even if `r.between` is already a pos-tagged string (see line 199 of /BREDS/Sentence.py)

**Comment by davidsbatista** [comment]
Please see issue https://github.com/davidsbatista/BREDS/issues/5.
