### ISSUE TITLE
the system is not working with tags other than "LOC", "ORG" and "PER"

### ISSUE THREAD

**Issue by alajlan66** [davidsbatista/BREDS#7]
Hello:

When I want to extract a relation between two entities 'ORG' and 'Date' the system doesn't extract any relations. for example 
`<ORG>NOKIA</ORG>` founded in `<Date>1865</Date>`
However, when I change the 'Date' tag to 'LOC' or 'PER' it works perfectly for example
`<ORG>NOKIA</ORG>` founded in `<LOC>1865</LOC>`

NOTE: I changed the negative and positive file ( e1 to ORG and e2 to Date) but still the system can not extract any relation between ORG and Date

**Comment by davidsbatista** [comment]
Hi! Sorry for the late reply. Did you also changed the entity type at the top of the seeds file?

Example: https://github.com/davidsbatista/BREDS/blob/master/seeds_positive.txt

```
e1:ORG
e2:LOC
```

change to:

```
e1:ORG
e2:DATE
```

**Comment by alajlan66** [comment]
Hi, 

Yes, the problem still there even when I changed the tags.

**Comment by davidsbatista** [comment]
did you changed them both on the positive and negative seeds?

**Comment by alajlan66** [comment]
yes both of them

**Comment by davidsbatista** [comment]
I don't remember having any hard-coded tags, they should be read from the config file. How do the tags look like in your sentences file?

**Comment by davidsbatista** [comment]
I've discovered it, you have to keep the entity type characters all in upper case, due to a regex.

Example, instead of : `<Date>`, you need to do `<DATE>`
