### ISSUE TITLE
Possible error in selectivity calculation

### ISSUE THREAD

**Issue by davebulaval** [davidsbatista/BREDS#8]
In the [function](https://github.com/davidsbatista/BREDS/blob/master/BREDS/Pattern.py) `pattern.update_selectivity`, if you have the situation where you hit `s.e1 == t.e1` but not `s.e2 == t.e2` you will have `matched_both = False and matched_e1 = True`. Meaning that you will increment the negative length of the pattern. **BUT** you will also hit the 
`if matched_both is False: self.unknown += 1`. 

This will increment the negative and unknown length.

**Comment by davidsbatista** [comment]
Thanks for the issue, I've fixed that bug, and added simple tests cases, plus I refactored the code to run under python3.
